<!DOCTYPE html>
<html lang="en">
	<head>
		<!-- Generated by GameMaker:HTML5 http://http://www.yoyogames.com/gamemaker/html5 -->
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="apple-mobile-web-app-capable" content="yes" />
		<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;" />
		<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
		<meta charset="utf-8"/>

		<!-- Set the title bar of the page -->
		<title>Make it Grow</title>
		<link type="text/css" href="/persistence/css/ui-lightness/jquery-ui-1.8.21.custom.css" rel="Stylesheet" />
		<style>
			.errorMessage {
				color: red;
			}
			#login { font-size: 64%; }
			#registration { font-size: 64%; }
			#forgot { font-size: 64%; }
			h1 { font-size: 1.2em; margin: .6em 0; }
			
		</style>
		<!-- Set the background colour of the document -->
		<style>
			body {
				background: #222;
				color:#cccccc;
			}
			canvas {
				image-rendering: optimizeSpeed;
				-webkit-interpolation-mode: nearest-neighbor;
			}
		</style>
		<!--script type="text/javascript" src="/persistence/js/jquery-1.7.2.js"></script>
		<script type="text/javascript" src="/persistence/js/jquery-ui-1.8.21.custom.min.js"></script>
		<script type="text/javascript" src="/persistence/persistence.js"></script>
		<script type="text/javascript" src="/persistence/savegames.js"></script-->
		<script type="text/javascript">

			var _gaq = _gaq || [];
			_gaq.push(['_setAccount', 'UA-32180577-1']);
			_gaq.push(['_trackPageview']);

			(function() {
				var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
				ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
				var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
			})();

		</script>
	</head>

	<body>
			<!-- Facebook button scripting -->
			<!--div id="fb-root"></div>
			<script>(function(d, s, id) {
				var js, fjs = d.getElementsByTagName(s)[0];
				if (d.getElementById(id)) return;
				js = d.createElement(s); js.id = id;
				js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
				fjs.parentNode.insertBefore(js, fjs);
			}(document, 'script', 'facebook-jssdk'));</script-->

			<!-- Create the canvas element the game draws to -->
			<canvas id="canvas" width="800" height="600">
			   <p>Your browser doesn't support HTML5 canvas.</p>
			</canvas>

			<!-- Facebook "Like" Button -->
			<!--div class="fb-like" data-href="http://playthegreendream.com/" data-send="true" data-layout="button_count" data-width="450" data-show-faces="false" data-font="arial"></div-->

		<!--input type="button" value="logout" onclick="javascript:logout()" -->

		<!-- Run the game code -->
		<script type="text/javascript" src="/game/agrigame1-98.js?BDRAC=1479659675"></script>
	</body>
</html>
